"""
This type stub file was generated by pyright.
"""

from .oidc import Client, IdTokenError
from .assertion import JwtAssertionCreator, JwtSigner
from .authcode import AuthCodeReceiver

__version__ = ...
