"""
This type stub file was generated by pyright.
"""

logger = ...
class AssertionCreator:
    def create_normal_assertion(self, audience, issuer, subject, expires_at=..., expires_in=..., issued_at=..., assertion_id=..., **kwargs):
        """Create an assertion in bytes, based on the provided claims.

        All parameter names are defined in https://tools.ietf.org/html/rfc7521#section-5
        except the expires_in is defined here as lifetime-in-seconds,
        which will be automatically translated into expires_at in UTC.
        """
        ...
    
    def create_regenerative_assertion(self, audience, issuer, subject=..., expires_in=..., **kwargs): # -> AutoRefresher:
        """Create an assertion as a callable,
        which will then compute the assertion later when necessary.

        This is a useful optimization to reuse the client assertion.
        """
        ...
    


class AutoRefresher:
    """Cache the output of a factory, and auto-refresh it when necessary. Usage::

        r = AutoRefresher(time.time, expires_in=5)
        for i in range(15):
            print(r())  # the timestamp change only after every 5 seconds
            time.sleep(1)
    """
    def __init__(self, factory, expires_in=...) -> None:
        ...
    
    def __call__(self): # -> None:
        ...
    


class JwtAssertionCreator(AssertionCreator):
    def __init__(self, key, algorithm, sha1_thumbprint=..., headers=..., *, sha256_thumbprint=...) -> None:
        """Construct a Jwt assertion creator.

        Args:

            key (str):
                An unencrypted private key for signing, in a base64 encoded string.
                It can also be a cryptography ``PrivateKey`` object,
                which is how you can work with a previously-encrypted key.
                See also https://github.com/jpadilla/pyjwt/pull/525
            algorithm (str):
                "RS256", etc.. See https://pyjwt.readthedocs.io/en/latest/algorithms.html
                RSA and ECDSA algorithms require "pip install cryptography".
            sha1_thumbprint (str): The x5t aka X.509 certificate SHA-1 thumbprint.
            headers (dict): Additional headers, e.g. "kid" or "x5c" etc.
            sha256_thumbprint (str): The x5t#S256 aka X.509 certificate SHA-256 thumbprint.
        """
        ...
    
    def create_normal_assertion(self, audience, issuer, subject=..., expires_at=..., expires_in=..., issued_at=..., assertion_id=..., not_before=..., additional_claims=..., **kwargs): # -> bytes | str:
        """Create a JWT Assertion.

        Parameters are defined in https://tools.ietf.org/html/rfc7523#section-3
        Key-value pairs in additional_claims will be added into payload as-is.
        """
        ...
    


Signer = AssertionCreator
JwtSigner = JwtAssertionCreator
