"""
This type stub file was generated by pyright.
"""

from .application import ClientApplication, ConfidentialClientApplication, PublicClientApplication
from .oauth2cli.oidc import IdTokenError, Prompt
from .sku import __version__
from .token_cache import SerializableTokenCache, TokenCache
from .auth_scheme import PopAuthScheme
from .managed_identity import ArcPlatformNotSupportedError, ManagedIdentityClient, ManagedIdentityError, SystemAssignedManagedIdentity, UserAssignedManagedIdentity
from .oauth2cli.oauth2 import BrowserInteractionTimeoutError

