"""
This type stub file was generated by pyright.
"""

logger = ...
AZURE_US_GOVERNMENT = ...
AZURE_CHINA = ...
AZURE_PUBLIC = ...
WORLD_WIDE = ...
WELL_KNOWN_AUTHORITY_HOSTS = ...
WELL_KNOWN_B2C_HOSTS = ...
_CIAM_DOMAIN_SUFFIX = ...
class AuthorityBuilder:
    def __init__(self, instance, tenant) -> None:
        """A helper to save caller from doing string concatenation.

        Usage is documented in :func:`application.ClientApplication.__init__`.
        """
        ...
    
    def __str__(self) -> str:
        ...
    


class Authority:
    """This class represents an (already-validated) authority.

    Once constructed, it contains members named "*_endpoint" for this instance.
    TODO: It will also cache the previously-validated authority instances.
    """
    _domains_without_user_realm_discovery = ...
    def __init__(self, authority_url, http_client, validate_authority=..., instance_discovery=..., oidc_authority_url=...) -> None:
        """Creates an authority instance, and also validates it.

        :param validate_authority:
            The Authority validation process actually checks two parts:
            instance (a.k.a. host) and tenant. We always do a tenant discovery.
            This parameter only controls whether an instance discovery will be
            performed.
        """
        ...
    
    def user_realm_discovery(self, username, correlation_id=..., response=...): # -> Any | dict[Any, Any]:
        ...
    


def canonicalize(authority_or_auth_endpoint): # -> tuple[Any, Any, Any | str] | tuple[Any, Any, Any]:
    ...

def tenant_discovery(tenant_discovery_endpoint, http_client, **kwargs): # -> Any:
    ...

