"""
This type stub file was generated by pyright.
"""

class PopAuthScheme:
    HTTP_GET = ...
    HTTP_POST = ...
    HTTP_PUT = ...
    HTTP_DELETE = ...
    HTTP_PATCH = ...
    _HTTP_METHODS = ...
    def __init__(self, http_method=..., url=..., nonce=...) -> None:
        """Create an auth scheme which is needed to obtain a Proof-of-Possession token.

        :param str http_method:
            Its value is an uppercase http verb, such as "GET" and "POST".
        :param str url:
            The url to be signed.
        :param str nonce:
            The nonce came from resource's challenge.
        """
        ...
    


