"""
This type stub file was generated by pyright.
"""

"""This module is an adaptor to the underlying broker.
It relies on PyMsalRuntime which is the package providing broker's functionality.
"""
logger = ...
class RedirectUriError(ValueError):
    ...


class TokenTypeError(ValueError):
    ...


_redirect_uri_on_mac = ...
