"""
This type stub file was generated by pyright.
"""

class MsalError(Exception):
    msg = ...


class MsalServiceError(MsalError):
    msg = ...
    def __init__(self, *args, error: str, error_description: str, **kwargs) -> None:
        ...
    


