"""
This type stub file was generated by pyright.
"""

from .oauth2cli.http import Response

DEVICE_AUTH_GRANT = ...
class RetryAfterParser:
    FIELD_NAME_LOWER = ...
    def __init__(self, default_value=...) -> None:
        ...
    
    def parse(self, *, result, **ignored): # -> int:
        """Return seconds to throttle"""
        ...
    


class NormalizedResponse(Response):
    """A http response with the shape defined in Response,
    but contains only the data we will store in cache.
    """
    def __init__(self, raw_response) -> None:
        ...
    
    def raise_for_status(self): # -> None:
        ...
    


class ThrottledHttpClientBase:
    """Throttle the given http_client by storing and retrieving data from cache.

    This base exists so that:
    1. These base post() and get() will return a NormalizedResponse
    2. The base __init__() will NOT re-throttle even if caller accidentally nested ThrottledHttpClient.

    Subclasses shall only need to dynamically decorate their post() and get() methods
    in their __init__() method.
    """
    def __init__(self, http_client, *, http_cache=...) -> None:
        ...
    
    def post(self, *args, **kwargs): # -> NormalizedResponse:
        ...
    
    def get(self, *args, **kwargs): # -> NormalizedResponse:
        ...
    
    def close(self):
        ...
    


class ThrottledHttpClient(ThrottledHttpClientBase):
    """A throttled http client that is used by MSAL's non-managed identity clients."""
    def __init__(self, *args, default_throttle_time=..., **kwargs) -> None:
        """Decorate self.post() and self.get() dynamically"""
        ...
    


