"""
This type stub file was generated by pyright.
"""

logger = ...
_GRANT_TYPE_BROKER = ...
def is_subdict_of(small, big):
    ...

class TokenCache:
    """This is considered as a base class containing minimal cache behavior.

    Although it maintains tokens using unified schema across all MSAL libraries,
    this class does not serialize/persist them.
    See subclass :class:`SerializableTokenCache` for details on serialization.
    """
    class CredentialType:
        ACCESS_TOKEN = ...
        REFRESH_TOKEN = ...
        ACCOUNT = ...
        ID_TOKEN = ...
        APP_METADATA = ...
    
    
    class AuthorityType:
        ADFS = ...
        MSSTS = ...
    
    
    def __init__(self) -> None:
        ...
    
    def search(self, credential_type, target=..., query=..., *, now=...): # -> Generator[Any, Any, None]:
        """Returns a generator of matching entries.

        It is O(1) for AT hits, and O(n) for other types.
        Note that it holds a lock during the entire search.
        """
        ...
    
    def find(self, credential_type, target=..., query=..., *, now=...): # -> list[Any]:
        """Equivalent to list(search(...))."""
        ...
    
    def add(self, event, now=...): # -> None:
        """Handle a token obtaining event, and add tokens into cache."""
        ...
    
    def modify(self, credential_type, old_entry, new_key_value_pairs=...): # -> None:
        ...
    
    def remove_rt(self, rt_item): # -> None:
        ...
    
    def update_rt(self, rt_item, new_rt): # -> None:
        ...
    
    def remove_at(self, at_item): # -> None:
        ...
    
    def remove_idt(self, idt_item): # -> None:
        ...
    
    def remove_account(self, account_item): # -> None:
        ...
    


class SerializableTokenCache(TokenCache):
    """This serialization can be a starting point to implement your own persistence.

    This class does NOT actually persist the cache on disk/db/etc..
    Depending on your need,
    the following simple recipe for file-based, unencrypted persistence may be sufficient::

        import os, atexit, msal
        cache_filename = os.path.join(  # Persist cache into this file
            os.getenv(
                # Automatically wipe out the cache from Linux when user's ssh session ends.
                # See also https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/690
                "XDG_RUNTIME_DIR", ""),
            "my_cache.bin")
        cache = msal.SerializableTokenCache()
        if os.path.exists(cache_filename):
            cache.deserialize(open(cache_filename, "r").read())
        atexit.register(lambda:
            open(cache_filename, "w").write(cache.serialize())
            # Hint: The following optional line persists only when state changed
            if cache.has_state_changed else None
            )
        app = msal.ClientApplication(..., token_cache=cache)
        ...

    Alternatively, you may use a more sophisticated cache persistence library,
    `MSAL Extensions <https://github.com/AzureAD/microsoft-authentication-extensions-for-python>`_,
    which provides token cache persistence with encryption, and more.

    :var bool has_state_changed:
        Indicates whether the cache state in the memory has changed since last
        :func:`~serialize` or :func:`~deserialize` call.
    """
    has_state_changed = ...
    def add(self, event, **kwargs): # -> None:
        ...
    
    def modify(self, credential_type, old_entry, new_key_value_pairs=...): # -> None:
        ...
    
    def deserialize(self, state: Optional[str]) -> None:
        """Deserialize the cache from a state previously obtained by serialize()"""
        ...
    
    def serialize(self) -> str:
        """Serialize the current cache state into a string."""
        ...
    


