"""
This type stub file was generated by pyright.
"""

logger = ...
def send_request(username, password, cloud_audience_urn, endpoint_address, soap_action, http_client, **kwargs): # -> dict[str, Any]:
    ...

def escape_password(password):
    ...

def wsu_time_format(datetime_obj):
    ...

